SELECT DATE_FORMAT(OS.SALES_DATE, '%Y') AS YEAR,
       DATE_FORMAT(OS.SALES_DATE, '%m') AS MONTH,
       COUNT(DISTINCT(UI.USER_ID)) AS PUCHASED_USERS,
       ROUND(COUNT(DISTINCT(UI.USER_ID)) / (SELECT COUNT(DISTINCT(UI.USER_ID))
                                             FROM USER_INFO UI
                                             WHERE UI.JOINED LIKE '2021%') ,1) AS PUCHASED_RATIO
       
FROM ONLINE_SALE OS JOIN USER_INFO UI ON OS.USER_ID = UI.USER_ID
WHERE UI.JOINED LIKE '2021%'
GROUP BY 1, 2
ORDER BY 1, 2