-- 코드를 입력하세요
SELECT MONTH(start_date), car_id, COUNT(CNT)
FROM (SELECT *, COUNT(HISTORY_ID) OVER(PARTITION BY CAR_ID) AS CNT
      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
      WHERE start_date BETWEEN '2022-08-01' AND '2022-10-31') A
WHERE CNT >= 5
GROUP BY 1,2
ORDER BY 1, 2 DESC
