-- 코드를 작성해주세요
WITH EMP AS
(SELECT ID, PERCENT_RANK() over (ORDER BY SIZE_OF_COLONY DESC) AS COLONY_PERCENT
FROM ECOLI_DATA)

SELECT ID, CASE WHEN COLONY_PERCENT<=0.25 THEN 'CRITICAL'
                WHEN COLONY_PERCENT<=0.50 THEN 'HIGH'
                WHEN COLONY_PERCENT<=0.75 THEN 'MEDIUM'
            ELSE "LOW" 
            END AS COLONY_NAME
FROM EMP
ORDER BY ID ASC