SELECT B.HISTORY_ID, ROUND(A.DAILY_FEE*(DATEDIFF(B.END_DATE,B.START_DATE)+1)*(1-
CASE
    WHEN DATEDIFF(END_DATE,START_DATE)+1 >= 90
        THEN (SELECT DISCOUNT_RATE
                             FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN 
                             WHERE DURATION_TYPE='90일 이상' AND CAR_TYPE='트럭')
    WHEN DATEDIFF(END_DATE,START_DATE)+1 >= 30 
        THEN (SELECT DISCOUNT_RATE
                             FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN 
                             WHERE DURATION_TYPE='30일 이상' AND CAR_TYPE='트럭')
    WHEN DATEDIFF(END_DATE,START_DATE)+1 >= 7 
        THEN (SELECT DISCOUNT_RATE
                             FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN 
                             WHERE DURATION_TYPE='7일 이상' AND CAR_TYPE='트럭')
    ELSE 0
END /100)) DIFF
FROM CAR_RENTAL_COMPANY_CAR A JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B ON A.CAR_ID=B.CAR_ID
WHERE A.CAR_TYPE='트럭'
ORDER BY 2 DESC, 1 DESC
