# -- 코드를 작성해주세요
# WITH EMP AS
# (SELECT FISH_TYPE
# FROM FISH_INFO
# GROUP BY FISH_TYPE
# HAVING AVG(IF(LENGTH<=10, 10,LENGTH))>=33)

# SELECT COUNT(FISH_TYPE) AS FISH_COUNT, MAX(LENGTH) AS MAX_LENGTH, FISH_TYPE
# FROM FISH_INFO
# WHERE FISH_TYPE IN (SELECT FISH_TYPE
#                    FROM EMP)
# GROUP BY FISH_TYPE
# ORDER BY FISH_TYPE ASC

SELECT COUNT(*) AS FISH_COUNT, MAX(LENGTH) AS MAX_LENGTH, FISH_TYPE
FROM FISH_INFO
GROUP BY FISH_TYPE
HAVING AVG(IFNULL(LENGTH,10)) >= 33
ORDER BY FISH_TYPE ASC;

